name: Modules mirroring to S3

on:
    push:
        branches:
            - master
            - ENT-7665

    workflow_dispatch:

jobs:

    build:

        runs-on: ubuntu-latest

        steps:

            - name: Checks-out repository
              uses: actions/checkout@v2

            - name: Setup Node.js environment
              uses: actions/setup-node@v2.4.1

            - name: Install node dependencies
              run: npm install

            - name: Update version.json
              run: grunt versioning

            - name: Upload modules to S3
              run: grunt upload

            - uses: peter-evans/create-pull-request@v3
              name: pull-request
              with:
                token: ${{ secrets.PAT }}
                commit-message: Update report
                committer: GitHub <noreply@github.com>
                author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
                signoff: false
                branch: autocommit
                delete-branch: true
                title: 'Updated versions.json'
                body: ""
                labels: |
                  actions
                  automated pr
                assignees: aleksandrychev
                reviewers: aleksandrychev
                draft: false
