name: Modules mirroring to S3

on:
    push:
        branches:
            - master
            - ENT-7665

    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checks-out repository
              uses: actions/checkout@v2

            - name: Setup Node.js environment
              uses: actions/setup-node@v2.4.1

            - name: Install node dependencies
              run: npm install

            - name: Update version.json
              run: grunt versioning

            - name: Commit version.json
              run: |
                git config user.name 'GitHub'
                git config user.email '<noreply@github.com>'
                git add versions.json
                git commit -m "Updated versions.json"

            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v3
              with:
                title: Chnages by mirroring action
                reviewers: aleksandrychev
                branch: mirroring/path

            - name: Upload modules to S3
              run: grunt upload
