name: Modules mirroring to S3

on:
    push:
        branches:
            - master
            - ENT-7665

    workflow_dispatch:

jobs:

    build:

        runs-on: ubuntu-latest

        steps:
            -
            - name: Checks-out repository
            - uses: actions/checkout@v2

            - name: Setup Node.js environment
              uses: actions/setup-node@v2.4.1

            - name: Install node dependencies
              run: |
                  npm install
                  npm install -g grunt-cli

            - name: Upload modules to S3
              run: grunt upload
