name: Modules mirroring to S3

on:
    push:
        branches:
            - master
            - ENT-7665
        paths:
          - index.json

    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checks-out repository
              uses: actions/checkout@v2

            - name: Setup Node.js environment
              uses: actions/setup-node@v2.4.1

            - name: Install node dependencies
              run: npm install

            - name: Upload modules to S3
              run: grunt upload

            - name: Commit version.json
              run: |
                git config user.name 'GitHub'
                git config user.email '<noreply@github.com>'
                git add versions.json
                git commit -m "Updated versions.json" || echo "versions.json is not changed"

            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v3
              with:
                title: Changes by mirroring action
                body: Updated versions.json and checksums.json
                reviewers: aleksandrychev
                branch: mirroring/path

