name: Modules mirroring to S3

on:
    push:
        branches:
            - master
            - ENT-7665

    workflow_dispatch:

jobs:

    build:

        runs-on: ubuntu-latest

        steps:

            - name: Checks-out repository
              uses: actions/checkout@v2

            - name: Setup Node.js environment
              uses: actions/setup-node@v2.4.1

            - name: Install node dependencies
              run: npm install

            - name: Update version.json
              run: grunt versioning

            - name: Upload modules to S3
              run: grunt upload

            - name: Commit versions.json changes
              uses: EndBug/add-and-commit@v7
              with:
                default_author: github_actions
                message: 'Updated versions.json'
                add: 'versions.json'

            - uses: repo-sync/pull-request@v2
              name: pull-request
              with:
                destination_branch: "ENT-7665"
                pr_title: "Updated versions.json"
                pr_body: ""
                pr_reviewer: "aleksandrychev"
                pr_draft: false
                github_token: ${{ secrets.GITHUB_TOKEN }}
